`Machine Learning Clasificación y Regresión | Analía Elizabeth Gomory | Salta - 4400 - Argentina | 2025`

**by Analía Elizabeth Gomory**

* ae.gomory@gmail.com

* http://www.linkedin.com/in/elizabeth-gomory-9240b1217

* https://ae-gomory.itch.io

* https://github.com/ElizabethGomory

* https://www.credly.com/users/analia-gomory

* https://orcid.org/0009-0003-0498-7658

## Importación de librerías y Archivos

In [47]:
import pandas as pd
import numpy as np
import openpyxl as xl
df = pd.read_csv('AmesHousing.csv')

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

## Normalización de datos

In [48]:
df.head(10)

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900
5,6,527105030,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,195500
6,7,527127150,120,RL,41.0,4920,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,213500
7,8,527145080,120,RL,43.0,5005,Pave,NaN,IR1,HLS,...,0,NaN,NaN,NaN,0,1,2010,WD,Normal,191500
8,9,527146030,120,RL,39.0,5389,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,3,2010,WD,Normal,236500
9,10,527162130,60,RL,60.0,7500,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,189000

In [49]:
import sys
sys.path.append(r'Clase_3 y 4')

* Cuantificar datos NaN

In [50]:
import claseinfodf_2 as info
ruta_archivo = '/'
nombre_archivo = 'n.xlsx'
crea_archivo = 'NO'
informe = info.info_modulo(df)
informe.informacion_dataframe()

Tamaño: (2930, 82)


Variables nulos:
   Nombre Variable Cantidad de Nulos
0     Lot Frontage               490
1            Alley              2732
2     Mas Vnr Type              1775
3     Mas Vnr Area                23
4        Bsmt Qual                80
5        Bsmt Cond                80
6    Bsmt Exposure                83
7   BsmtFin Type 1                80
8     BsmtFin SF 1                 1
9   BsmtFin Type 2                81
10    BsmtFin SF 2                 1
11     Bsmt Unf SF                 1
12   Total Bsmt SF                 1
13      Electrical                 1
14  Bsmt Full Bath                 2
15  Bsmt Half Bath                 2
16    Fireplace Qu              1422
17     Garage Type               157
18   Garage Yr Blt               159
19   Garage Finish               159
20     Garage Cars                 1
21     Garage Area                 1
22     Garage Qual               159
23     Garage Cond               159
24         Pool QC              2917
25           Fence              2358
26    Misc Feature              2824


Variables NAN:
   Nombre Variable Cantidad de Nulos
0            Alley              2732
1     Mas Vnr Type              1775
2        Bsmt Qual                80
3        Bsmt Cond                80
4    Bsmt Exposure                83
5   BsmtFin Type 1                80
6   BsmtFin Type 2                81
7       Electrical                 1
8     Fireplace Qu              1422
9      Garage Type               157
10   Garage Finish               159
11     Garage Qual               159
12     Garage Cond               159
13         Pool QC              2917
14           Fence              2358
15    Misc Feature              2824


Informacion dataframe:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS SubClass      2930 non-null   int64
 3   MS Zoning        2930 non-null   object
 4   Lot Frontage     2440 non-null   float64
 5   Lot Area         2930 non-null   int64
 6   Street           2930 non-null   object
 7   Alley            198 non-null    object
 8   Lot Shape        2930 non-null   object
 9   Land Contour     2930 non-null   object
 10  Utilities        2930 non-null   object
 11  Lot Config       2930 non-null   object
 12  Land Slope       2930 non-null   object
 13  Neighborhood     2930 non-null   object
 14  Condition 1      2930 non-null   object
 15  Condition 2      2930 non-null   object
 16  Bldg Type        2930 non-null   object
 17  House Style      2930 non-null   object
 18  Overall Qual     2930 non-null   int64
 19  Overall Cond     2930 non-null   int64
 20  Year Built       2930 non-null   int64
 21  Year Remod/Add   2930 non-null   int64
 22  Roof Style       2930 non-null   object
 23  Roof Matl        2930 non-null   object
 24  Exterior 1st     2930 non-null   object
 25  Exterior 2nd     2930 non-null   object
 26  Mas Vnr Type     1155 non-null   object
 27  Mas Vnr Area     2907 non-null   float64
 28  Exter Qual       2930 non-null   object
 29  Exter Cond       2930 non-null   object
 30  Foundation       2930 non-null   object
 31  Bsmt Qual        2850 non-null   object
 32  Bsmt Cond        2850 non-null   object
 33  Bsmt Exposure    2847 non-null   object
 34  BsmtFin Type 1   2850 non-null   object
 35  BsmtFin SF 1     2929 non-null   float64
 36  BsmtFin Type 2   2849 non-null   object
 37  BsmtFin SF 2     2929 non-null   float64
 38  Bsmt Unf SF      2929 non-null   float64
 39  Total Bsmt SF    2929 non-null   float64
 40  Heating          2930 non-null   object
 41  Heating QC       2930 non-null   object
 42  Central Air      2930 non-null   object
 43  Electrical       2929 non-null   object
 44  1st Flr SF       2930 non-null   int64
 45  2nd Flr SF       2930 non-null   int64
 46  Low Qual Fin SF  2930 non-null   int64
 47  Gr Liv Area      2930 non-null   int64
 48  Bsmt Full Bath   2928 non-null   float64
 49  Bsmt Half Bath   2928 non-null   float64
 50  Full Bath        2930 non-null   int64
 51  Half Bath        2930 non-null   int64
 52  Bedroom AbvGr    2930 non-null   int64
 53  Kitchen AbvGr    2930 non-null   int64
 54  Kitchen Qual     2930 non-null   object
 55  TotRms AbvGrd    2930 non-null   int64
 56  Functional       2930 non-null   object
 57  Fireplaces       2930 non-null   int64
 58  Fireplace Qu     1508 non-null   object
 59  Garage Type      2773 non-null   object
 60  Garage Yr Blt    2771 non-null   float64
 61  Garage Finish    2771 non-null   object
 62  Garage Cars      2929 non-null   float64
 63  Garage Area      2929 non-null   float64
 64  Garage Qual      2771 non-null   object
 65  Garage Cond      2771 non-null   object
 66  Paved Drive      2930 non-null   object
 67  Wood Deck SF     2930 non-null   int64
 68  Open Porch SF    2930 non-null   int64
 69  Enclosed Porch   2930 non-null   int64
 70  3Ssn Porch       2930 non-null   int64
 71  Screen Porch     2930 non-null   int64
 72  Pool Area        2930 non-null   int64
 73  Pool QC          13 non-null     object
 74  Fence            572 non-null    object
 75  Misc Feature     106 non-null    object
 76  Misc Val         2930 non-null   int64
 77  Mo Sold          2930 non-null   int64
 78  Yr Sold          2930 non-null   int64
 79  Sale Type        2930 non-null   object
 80  Sale Condition   2930 non-null   object
 81  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(28), object(43)
memory usage: 1.8+ MB
None


Datos:

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
1593,1594,923225080,120,RM,NaN,4224,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,124000
2604,2605,535382020,190,RL,60.0,10800,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,5,2006,ConLD,Normal,160000
2522,2523,533350050,20,RL,68.0,50271,Pave,NaN,IR1,Low,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,385000
2195,2196,909176170,90,RL,60.0,10890,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,Shed,1512,1,2007,WD,AdjLand,150000
851,852,907196060,20,RL,75.0,11166,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,7,2009,WD,Family,201000
185,186,902329030,70,RM,50.0,9000,Pave,Grvl,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,240000
2784,2785,907202140,20,RL,69.0,9920,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,128500
730,731,903201080,50,RL,55.0,7264,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,10,2009,WD,Normal,205000
2371,2372,527451460,160,RM,21.0,1680,Pave,NaN,Reg,Lvl,...,0,NaN,GdPrv,NaN,0,10,2006,WD,Normal,108000
1540,1541,909428170,20,RL,56.0,26073,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,4,2008,WD,Normal,236500

No se realiza creación de Archivo

Reordenar datos NaN de mayor a menor

In [54]:
missing_data = df.isnull().sum().sort_values(ascending=False)
missing_data = missing_data[missing_data > 0]  
missing_data

Pool QC           2917
Misc Feature      2824
Alley             2732
Fence             2358
Mas Vnr Type      1775
Fireplace Qu      1422
Lot Frontage       490
Garage Cond        159
Garage Finish      159
Garage Yr Blt      159
Garage Qual        159
Garage Type        157
Bsmt Exposure       83
BsmtFin Type 2      81
Bsmt Qual           80
Bsmt Cond           80
BsmtFin Type 1      80
Mas Vnr Area        23
Bsmt Full Bath       2
Bsmt Half Bath       2
BsmtFin SF 1         1
Garage Cars          1
Electrical           1
Total Bsmt SF        1
Bsmt Unf SF          1
BsmtFin SF 2         1
Garage Area          1
dtype: int64

Limpieza de datos

In [55]:
# Decidí eliminar solo las columnas con más del 50% de valores nulos, de lo contrario, me quedaría sin datos a entrenar
threshold = 0.5 * len(df)
columns_drop = missing_data[missing_data > threshold].index.tolist()
df_cleaned = df.drop(columns=columns_drop)

In [56]:
df_cleaned = df_cleaned.dropna()
df_cleaned.shape

(1156, 77)

## Entrenamiento y Validación

In [58]:
X = df_cleaned.drop("SalePrice", axis=1)
y = df_cleaned["SalePrice"]

X_encoded = pd.get_dummies(X, drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42)

# Regresión Lineal

In [59]:
model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

comparasion = pd.DataFrame({
    "Precio Real": y_test.values[:5],
    "Predicción": y_pred[:5].round(2)
})
comparasion

   Precio Real  Predicción
0       125500   116780.69
1       149500   182503.18
2       266500   193718.58
3       172500   170276.69
4       188500   199928.94

* Estimación del valor del modelo de Regresión - MSE

In [60]:
mse = mean_squared_error(y_test, y_pred)

print("MSE con Regresión Lineal:", mse)

MSE con Regresión Lineal: 1611531858.4456904

# Mejora del modelo con RandomForestRegressor

In [61]:
x = df_cleaned.drop("SalePrice", axis=1)
y = df_cleaned["SalePrice"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train, y_train)
y_rf_pred = rf_model.predict(X_test)

rf_mse = mean_squared_error(y_test, y_rf_pred)
print("MSE con Random Forest:", rf_mse)

MSE con Random Forest: 1006510023.3315009